"""Phase 3 wrap-up — 4-row x 6-column comparison sheet.

Rows  : FP16 baseline / Sprint 2 TRT implicit / Phase 2 Packed+LoRA / Phase 3 B1-c TRT INT8
Cols  : 6 prompts. Indices 03/04/60 come from the COCO eval set tracked on the
        ``sean`` branch / local 64-prompt dirs; indices 65/66/67 are custom prompts
        ("Portrait of a blonde woman", "A cyberpunk city skyline at night, neon
        lights", "A fluffy cat sitting on a windowsill"), generated by:

          - EC2  (utils/gen_custom_3backends.py) for FP16 / Sprint 2 / Phase 3
          - local (utils/gen_custom_phase2.py)    for the Phase 2 row
"""
from __future__ import annotations
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
EVALS = ROOT / "evals" / "eval_output"
CUSTOM = EVALS / "custom_showcase"
OUT = EVALS / "showcase_4row.jpg"

PROMPT_IDX = ["65", "67", "03", "04", "66", "60"]
CUSTOM_IDX = {"65", "66", "67"}

# Sources for non-custom indices (dataset prompts) — all local paths.
DATASET_ROWS = [
    # (row_label, dir, file-prefix)
    ("FP16 baseline\n(4.9 GB, MSE 0)",
     EVALS / "images" / "sdxl_lightning_gptq_blockmp_ffn4_attn8_conv8", "fp16_"),
    ("Sprint 2 TRT implicit\n(4.6 GB, MSE 0.014,\n~all FP16 inside)",
     EVALS / "images" / "trt_implicit_64p", "trt_e2e_"),
    ("Phase 2 Packed+Q-LoRA\n(1.5 + 0.17 GB,\nMSE 0.008, PyTorch)",
     ROOT / "quantization" / "main" / "packed" / "qlora_eval_deepconvw8_lora_a4", "packed_lora_r16_"),
    ("Phase 3 B1-c TRT INT8\n(2.66 GB, MSE 0.037,\n0.98 s/img on A10G)",
     EVALS / "images" / "trt_b1c_64p", "trt_e2e_"),
]

# Sources for the custom indices — local dirs filled by separate gen scripts.
CUSTOM_ROW_DIRS = [
    CUSTOM / "fp16",          # row 1
    CUSTOM / "trt_implicit",  # row 2
    CUSTOM / "packed_lora",   # row 3 (user runs locally)
    CUSTOM / "trt_b1c",       # row 4
]
CUSTOM_PREFIXES = ["fp16_", "trt_implicit_", "packed_lora_", "trt_b1c_"]

THUMB = 320
PAD = 8
LABEL_W = 220


def local_first_path(dir_: Path, prefix_idx: str) -> Path:
    matches = sorted(dir_.glob(f"{prefix_idx}*.png"))
    if not matches:
        raise FileNotFoundError(f"no match for {prefix_idx} in {dir_}")
    return matches[0]


def thumb(im: Image.Image) -> Image.Image:
    im = im.copy()
    im.thumbnail((THUMB, THUMB), Image.LANCZOS)
    return im


def placeholder(label: str) -> Image.Image:
    """Gray placeholder for missing custom row (e.g. Phase 2 not yet generated)."""
    im = Image.new("RGB", (THUMB, THUMB), (220, 220, 220))
    d = ImageDraw.Draw(im)
    try:
        font = ImageFont.truetype("arial.ttf", 14)
    except OSError:
        font = ImageFont.load_default()
    d.multiline_text((20, THUMB // 2 - 20), f"missing\n{label}", fill=(80, 80, 80), font=font, align="center")
    return im


def load_cell(row_idx: int, prompt_idx: str) -> Image.Image:
    row_label, dir_, dataset_prefix = DATASET_ROWS[row_idx]
    if prompt_idx in CUSTOM_IDX:
        cdir = CUSTOM_ROW_DIRS[row_idx]
        pfx = f"{CUSTOM_PREFIXES[row_idx]}{prompt_idx}"
        try:
            return thumb(Image.open(local_first_path(cdir, pfx)).convert("RGB"))
        except FileNotFoundError:
            return placeholder(f"{cdir.name}/\n{pfx}*")
    try:
        return thumb(Image.open(local_first_path(dir_, f"{dataset_prefix}{prompt_idx}")).convert("RGB"))
    except FileNotFoundError:
        return placeholder(f"{dir_.name}/\n{dataset_prefix}{prompt_idx}*")


def main() -> None:
    N = len(PROMPT_IDX)
    W = LABEL_W + PAD + (THUMB + PAD) * N
    H = PAD + (THUMB + PAD) * len(DATASET_ROWS)
    sheet = Image.new("RGB", (W, H), "white")
    draw = ImageDraw.Draw(sheet)
    try:
        font = ImageFont.truetype("arial.ttf", 14)
    except OSError:
        font = ImageFont.load_default()

    for ri, row in enumerate(DATASET_ROWS):
        y = PAD + ri * (THUMB + PAD)
        for li, line in enumerate(row[0].split("\n")):
            draw.text((8, y + 12 + li * 18), line, fill="black", font=font)
        for ci, idx in enumerate(PROMPT_IDX):
            sheet.paste(load_cell(ri, idx),
                        (LABEL_W + PAD + ci * (THUMB + PAD), y))

    OUT.parent.mkdir(parents=True, exist_ok=True)
    sheet.save(OUT, quality=85, optimize=True)
    print(f"wrote {OUT} ({OUT.stat().st_size/1024:.0f} KB)")


if __name__ == "__main__":
    main()
